//! This code was AUTOGENERATED using the Codama library.
use crate::types::Shareholder;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct TradeEventEvent {
    pub mint: Pubkey,
    pub sol_amount: u64,
    pub token_amount: u64,
    pub is_buy: bool,
    pub user: Pubkey,
    pub timestamp: i64,
    pub virtual_sol_reserves: u64,
    pub virtual_token_reserves: u64,
    pub real_sol_reserves: u64,
    pub real_token_reserves: u64,
    pub fee_recipient: Pubkey,
    pub fee_basis_points: u64,
    pub fee: u64,
    pub creator: Pubkey,
    pub creator_fee_basis_points: u64,
    pub creator_fee: u64,
    pub track_volume: bool,
    pub total_unclaimed_tokens: u64,
    pub total_claimed_tokens: u64,
    pub current_sol_volume: u64,
    pub last_update_timestamp: i64,
    pub ix_name: String,
    pub mayhem_mode: bool,
    pub cashback_fee_basis_points: u64,
    pub cashback: u64,
    /// Appended by later pump IDLs. A quote-token curve reports its quote
    /// side here (`quote_mint` default means SOL, and the sol_* fields then
    /// carry the quote amounts); a holder-reward curve reports the share of
    /// the trade paid to holders.
    pub buyback_fee_basis_points: u64,
    pub buyback_fee: u64,
    pub shareholders: Vec<Shareholder>,
    pub quote_mint: Pubkey,
    pub quote_amount: u64,
    pub virtual_quote_reserves: u64,
    pub real_quote_reserves: u64,
    pub holder_rewards_bps: u64,
    pub holder_rewards: u64,
}

impl TradeEventEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [189, 219, 127, 211, 78, 230, 97, 238] {
            return None;
        }

        // Zero-pad so events emitted before the appended fields still decode,
        // with the missing tail reading as 0/default and no shareholders.
        let mut padded = data[8..].to_vec();
        padded.extend_from_slice(&[0u8; APPENDED_LEN]);
        let mut data_slice = padded.as_slice();

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

/// buyback (16) + empty shareholders (4) + quote_mint (32) + quote amounts (24)
/// + holder rewards (16).
const APPENDED_LEN: usize = 16 + 4 + 32 + 24 + 16;

#[cfg(test)]
mod tests {
    use super::*;

    const DISCRIMINATOR: [u8; 8] = [189, 219, 127, 211, 78, 230, 97, 238];

    fn fixture() -> TradeEventEvent {
        TradeEventEvent {
            mint: Pubkey::new_unique(),
            sol_amount: 0,
            token_amount: 6_884_670_975_712,
            is_buy: false,
            user: Pubkey::new_unique(),
            timestamp: 1_789_405_285,
            virtual_sol_reserves: 0,
            virtual_token_reserves: 402_301_163_638_811,
            real_sol_reserves: 0,
            real_token_reserves: 122_401_163_638_811,
            fee_recipient: Pubkey::new_unique(),
            fee_basis_points: 95,
            fee: 214_231_810,
            creator: Pubkey::new_unique(),
            creator_fee_basis_points: 300,
            creator_fee: 676_521_504,
            track_volume: false,
            total_unclaimed_tokens: 0,
            total_claimed_tokens: 0,
            current_sol_volume: 0,
            last_update_timestamp: 0,
            ix_name: "sell".to_string(),
            mayhem_mode: false,
            cashback_fee_basis_points: 0,
            cashback: 0,
            buyback_fee_basis_points: 5_000,
            buyback_fee: 107_115_905,
            shareholders: vec![Shareholder {
                address: Pubkey::new_unique(),
                share_bps: 10_000,
            }],
            quote_mint: Pubkey::new_unique(),
            quote_amount: 22_550_716_789,
            virtual_quote_reserves: 1_295_185_401_205,
            real_quote_reserves: 809_580_001_806,
            holder_rewards_bps: 300,
            holder_rewards: 676_521_504,
        }
    }

    fn event_data(event: &TradeEventEvent) -> Vec<u8> {
        let mut data = DISCRIMINATOR.to_vec();
        data.extend_from_slice(&borsh::to_vec(event).expect("serialize"));
        data
    }

    #[test]
    fn decodes_current_layout() {
        let event = fixture();
        assert_eq!(TradeEventEvent::decode(&event_data(&event)), Some(event));
    }

    #[test]
    fn decodes_events_without_holder_rewards() {
        let event = fixture();
        let mut data = event_data(&event);
        data.truncate(data.len() - 16);

        let decoded = TradeEventEvent::decode(&data).expect("event decodes");
        assert_eq!(decoded.holder_rewards_bps, 0);
        assert_eq!(decoded.holder_rewards, 0);
        assert_eq!(decoded.quote_mint, event.quote_mint);
        assert_eq!(decoded.real_quote_reserves, event.real_quote_reserves);
    }

    #[test]
    fn decodes_legacy_layout_without_appended_fields() {
        let mut event = fixture();
        event.shareholders.clear();
        let mut data = event_data(&event);
        data.truncate(data.len() - APPENDED_LEN);

        let decoded = TradeEventEvent::decode(&data).expect("legacy event decodes");
        assert_eq!(decoded.quote_mint, Pubkey::default());
        assert!(decoded.shareholders.is_empty());
        assert_eq!(decoded.quote_amount, 0);
        assert_eq!(decoded.holder_rewards_bps, 0);
        assert_eq!(decoded.creator_fee_basis_points, 300);
        assert_eq!(decoded.ix_name, "sell");
    }
}
